hooks:
  GriefDefender:
    enabled: false
    ignoredClaims: []
      # - "9ae58371-3857-4ec8-9d19-f6d24c2f57c7"
  DeluxeCombat:
    enabled: false
itemEntries:
  enabled: true
  '1':
    enabled: true
    type: "EXPLOSIVE_ARROW" # Don't change
    key: "EXPLOSIVEBOW"
    cooldown: 4
    hunger: 6
    shotRandomness: 0.2
    extraDamage: 0.0
    ammoItem: "TNT"
    item: "BOW"
    name: "&6Explosive Bow"
    lore:
      - "&8&oRequires TNT and Arrows"
    hideEnchants: false
    enchantments:
      - "MENDING:1"
  '2':
    enabled: true
    type: "LIGHTNING_PEARL" # Don't change
    key: "LIGHTNINGGUN"
    cooldown: 4
    hunger: 4
    shotRandomness: 0.2
    extraDamage: 7.0
    ammoItem: "ENDER_PEARL"
    item: "ECHO_SHARD"
    name: "&6Lightning Gun"
    lore:
      - "&8&oRequires Ender Pearl"
    hideEnchants: true
    enchantments:
      - "MENDING:1"
  '3':
    enabled: true
    type: "RANDOM_POTION" # Don't change
    key: "MAGICWAND"
    cooldown: 4
    hunger: 4
    shotRandomness: 0.1
    extraDamage: 3.0
    ammoItem: "POTION"
    item: "BRUSH"
    name: "&6Magic Wand"
    lore:
      - "&8&oRequires Potion or Water Bottle"
    hideEnchants: true
    enchantments:
      - "MENDING:1"