hooks:
  GriefDefender:
    enabled: false
    ignoredClaims: []
      # - "9ae58371-3857-4ec8-9d19-f6d24c2f57c7"
  DeluxeCombat:
    enabled: false
itemEntries:
  enabled: true
  '1':
    enabled: true
    type: "EXPLOSIVE_ARROW" # Don't change
    key: "EXPLOSIVEBOW"
    givePerm: "item64.give"
    usePerm: "item64.use"
    cooldown: 8
    hunger: 4
    name: "&6Explosive Bow"
    item: "BOW"
    ammoItem: "TNT"
    glowing: true
    lore:
      - "&8&oRequires TNT and Arrows"
  '2':
    enabled: true
    type: "LIGHTNING_PEARL" # Don't change
    key: "LIGHTNINGGUN"
    givePerm: "item64.give"
    usePerm: "item64.use"
    cooldown: 8
    hunger: 4
    name: "&6Lightning Gun"
    item: "ECHO_SHARD"
    ammoItem: "ENDER_PEARL"
    glowing: true
    lore:
      - "&8&oRequires Ender Pearl"
  '3':
    enabled: true
    type: "RANDOM_POTION" # Don't change
    key: "MAGICWAND"
    givePerm: "item64.give"
    usePerm: "item64.use"
    cooldown: 8
    hunger: 4
    name: "&6Magic Wand"
    item: "BRUSH"
    ammoItem: "POTION"
    glowing: true
    lore:
      - "&8&oRequires Potion or Water Bottle"