# Item64 v0.2.3-beta by @tbm00

hooks:
  Vault:
    enabled: false
  GriefDefender:
    enabled: false
    ignoredClaims: []
      # - "9ae58371-3857-4ec8-9d19-f6d24c2f57c7"
  DeluxeCombat:
    enabled: false

stopBlockPlace:
- "REDSTONE_TORCH"

itemEntries:
  enabled: true
  '1':
    enabled: true
    type: "FLAME_PARTICLE" # Don't change
    key: "FLAMETHROWER"
    givePerm: "item64.give.flamethrower"
    usePerm: "item64.use.flamethrower"
    moneyCost: 0.00
    hungerCost: 1
    cooldown: 0
    shotRandomness: 0.3
    extraDamage: 2.0
    ammoItem: "COAL"
    item: "REDSTONE_TORCH"
    name: "&6Flamethrower"
    lore:
      - "&8&oRequires Coal"
    hideEnchants: true
    enchantments:
      - "MENDING:1"
  '2':
    enabled: true
    type: "EXPLOSIVE_ARROW" # Don't change
    key: "EXPLOSIVE_CROSSBOW"
    givePerm: "item64.give.explosive_crossbow"
    usePerm: "item64.use.explosive_crossbow"
    moneyCost: 0.00
    hungerCost: 6
    cooldown: 1
    shotRandomness: 0.2
    extraDamage: 0.0
    ammoItem: "TNT"
    item: "CROSSBOW"
    name: "&6Explosive Crossbow"
    lore:
      - "&8&oRequires TNT and Arrows"
    hideEnchants: false
    enchantments:
      - "QUICK_CHARGE:4"
      - "MENDING:1"
  '3':
    enabled: true
    type: "LIGHTNING_PEARL" # Don't change
    key: "LIGHTNING_GUN"
    givePerm: "item64.give.lightning_gun"
    usePerm: "item64.use.lightning_gun"
    moneyCost: 0.00
    hungerCost: 4
    cooldown: 4
    shotRandomness: 0.2
    extraDamage: 7.0
    ammoItem: "ENDER_PEARL"
    item: "ECHO_SHARD"
    name: "&6Lightning Gun"
    lore:
      - "&8&oRequires Ender Pearl"
    hideEnchants: true
    enchantments:
      - "MENDING:1"
  '4':
    enabled: true
    type: "RANDOM_POTION" # Don't change
    key: "MAGIC_WAND"
    givePerm: "item64.give.magic_wand"
    usePerm: "item64.use.magic_wand"
    moneyCost: 0.00
    hungerCost: 4
    cooldown: 4
    shotRandomness: 0.1
    extraDamage: 2.0
    ammoItem: "POTION"
    item: "BRUSH"
    name: "&6Magic Wand"
    lore:
      - "&8&oRequires Potion or Water Bottle"
    hideEnchants: true
    enchantments:
      - "MENDING:1"
  '5':
    enabled: true
    type: "CONSUME_COMMANDS" # Don't change
    key: "HEALING_HONEY"
    givePerm: "item64.give.healing_honey"
    usePerm: "item64.use.healing_honey"
    moneyCost: 0.00
    hungerCost: 0
    cooldown: 60
    ammoItem: ""
    item: "HONEY_BOTTLE"
    name: "&6Healing Honey"
    lore:
      - "&eRestores health, hunger,"
      - "&eand removes potions effects"
    hideEnchants: true
    enchantments:
      - "UNBREAKING:1"
    removeConsumedItem: true
    consoleCommands:
      - "itm heal <player>"
  '6':
    enabled: true
    type: "CONSUME_EFFECTS" # Don't change
    key: "SUPERAPPLE"
    givePerm: "item64.give.superapple"
    usePerm: "item64.use.superapple"
    moneyCost: 0.00
    hungerCost: 0
    cooldown: 60
    ammoItem: ""
    item: "ENCHANTED_GOLDEN_APPLE"
    name: "&6Superapple"
    lore:
      - "&e30 mins of"
      - "&e Regeneration II"
      - "&e Resistance IV"
      - "&e Fire Resistance I"
      - "&e Strength II"
      - "&e Haste II"
      - "&e Jump Boost II"
      - "&e Speed I"
    hideEnchants: true
    enchantments:
      - "UNBREAKING:1"
    removeConsumedItem: true