# Item64 v0.2.19-beta by @tbm00
# https://github.com/tbm00/Item64

enabled: true

hooks:
  Vault:
    enabled: false
  GriefDefender:
    enabled: false
    ignoredClaims: []
  DeluxeCombat:
    enabled: false
    anchorExplosionPvpCheck: false # temporary fix that blocks respawn anchor usage if player or nearby players have pvp disabled

breakEvent:
  inactiveWorlds:
    - "world"
    - "world_nether"
    - "world_the_end"
  rewardBlockBreaking:
    enabled: false
    joinMessage: "&eWelcome! &6We're currently having our Halloween event -- break pumpkins to find candy!"
    joinMessageDelay: 5
    chance: 33.3
    blocks:
      - "PUMPKIN"
      - "CARVED_PUMPKIN"
      - "JACK_O_LANTERN"
  preventBlockPlacing:
    enabled: false
    message: "&cSorry, you cannot place that block during our event!"
    blocks:
      - "PUMPKIN"
      - "CARVED_PUMPKIN"
      - "JACK_O_LANTERN"
  preventBlockGrowth:
    enabled: false
    logInConsole: false
    blocks:
      - "PUMPKIN"

itemEntries:
  "1":
    key: "FLAMETHROWER"
    type: "FLAME_PARTICLE"
    enabled: true
    givePerm: "item64.give.pvp_item.flamethrower"
    usePerm: "item64.use.pvp_item.flamethrower"
    item:
      mat: "REDSTONE_TORCH"
      name: "&6Flamethrower"
      lore:
        - "&8&oRequires Coal"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
    usage:
      moneyCost: 0.00
      hungerCost: 1
      cooldown: 0
      ammoItem:
        mat: "COAL"
        removeAmmoItemOnUse: true
      projectile:
        shotRandomness: 0.42
        extraDamage: 3.0
  "2":
    key: "EXPLOSIVE_BOW"
    type: "EXPLOSIVE_ARROW"
    enabled: true
    givePerm: "item64.give.pvp_item.explosive_bow"
    usePerm: "item64.use.pvp_item.explosive_bow"
    item:
      mat: "BOW"
      name: "&6Explosive Bow"
      lore:
        - "&8&oRequires Bedrock and Arrows"
      hideEnchants: false
      enchantments:
        - "UNBREAKING:5"
        - "MENDING:1"
    usage:
      moneyCost: 0.00
      hungerCost: 0
      cooldown: 0
      ammoItem:
        mat: "BEDROCK"
        removeAmmoItemOnUse: true
      projectile:
        shotRandomness: 0.32
        extraDamage: 0.0
        explosiveArrow:
          power: 96
  "3":
    key: "EXPLOSIVE_CROSSBOW"
    type: "EXPLOSIVE_ARROW"
    enabled: true
    givePerm: "item64.give.pvp_item.explosive_crossbow"
    usePerm: "item64.use.pvp_item.explosive_crossbow"
    item:
      mat: "CROSSBOW"
      name: "&6Explosive Crossbow"
      lore:
        - "&8&oRequires TNT and Arrows"
      hideEnchants: false
      enchantments:
        - "QUICK_CHARGE:5"
        - "MENDING:1"
    usage:
      moneyCost: 0.00
      hungerCost: 5
      cooldown: 2
      ammoItem:
        mat: "TNT"
        removeAmmoItemOnUse: true
      projectile:
        shotRandomness: 0.2
        extraDamage: 0.0
        explosiveArrow:
          power: 4
  "4":
    key: "LIGHTNING_GUN"
    type: "LIGHTNING_PEARL"
    enabled: true
    givePerm: "item64.give.pvp_item.lightning_gun"
    usePerm: "item64.use.pvp_item.lightning_gun"
    item:
      mat: "ECHO_SHARD"
      name: "&6Lightning Gun"
      lore:
        - "&8&oRequires Ender Pearls"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
    usage:
      moneyCost: 0.00
      hungerCost: 2
      cooldown: 2
      ammoItem:
        mat: "ENDER_PEARL"
        removeAmmoItemOnUse: true
      projectile:
        shotRandomness: 0.17
        extraDamage: 5.0
  "5":
    key: "MAGIC_WAND"
    type: "RANDOM_POTION"
    enabled: true
    givePerm: "item64.give.pvp_item.magic_wand"
    usePerm: "item64.use.pvp_item.magic_wand"
    item:
      mat: "BRUSH"
      name: "&6Magic Wand"
      lore:
        - "&9Left Click for Aggressive Effects"
        - "&9Right Click for Positive Effects"
        - "&8&oRequires Potions or Water Bottles"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
    usage:
      moneyCost: 0.00
      hungerCost: 2
      cooldown: 2
      ammoItem:
        mat: "POTION"
        removeAmmoItemOnUse: true
      projectile:
        shotRandomness: 0.17
        extraDamage: 6.0
        randomPotion:
          rightClickEffects:
            - "INCREASE_DAMAGE:1:30"
            - "HEAL:1:30"
            - "JUMP:1:30"
            - "SPEED:1:30"
            - "REGENERATION:1:30"
            - "FIRE_RESISTANCE:0:30"
            - "NIGHT_VISION:1:30"
            - "INVISIBILITY:0:30"
            - "ABSORPTION:1:30"
            - "SATURATION:1:30"
            - "SLOW_FALLING:1:30"
          leftClickEffects:
            - "SLOW:1:30"
            - "HARM:1:30"
            - "CONFUSION:0:30"
            - "BLINDNESS:0:30"
            - "HUNGER:1:30"
            - "WEAKNESS:1:30"
            - "POISON:1:30"
            - "LEVITATION:2:45"
            - "GLOWING:0:30"
  "6":
    key: "HEALING_HONEY"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.healing_honey"
    usePerm: "item64.use.candy.healing_honey"
    item:
      mat: "HONEY_BOTTLE"
      name: "&6Healing Honey"
      lore:
        - "&eRestores health, hunger,"
        - "&eand removes potions effects"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands:
          - "itm heal <player> -fx"
        effects: []
        actionBarMessage: "&aYou gobbled the honey!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found some healing honey!"
      giveRewardItem: true
      rewardCommands: []
  "7":
    key: "SUPERAPPLE"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.superapple"
    usePerm: "item64.use.candy.superapple"
    item:
      mat: "ENCHANTED_GOLDEN_APPLE"
      name: "&6Superapple"
      lore:
        - "&e30 mins of"
        - "&e  Regeneration II"
        - "&e  Absorption IV"
        - "&e  Resistance IV"
        - "&e  Fire Resistance"
        - "&e  Strength II"
        - "&e  Haste II"
        - "&e  Jump Boost II"
        - "&e  Speed I"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands:
          - "itm heal <player>"
        effects:
          - "REGENERATION:1:1800"
          - "ABSORPTION:3:1800"
          - "DAMAGE_RESISTANCE:3:1800"
          - "FIRE_RESISTANCE:0:1800"
          - "INCREASE_DAMAGE:1:1800"
          - "FAST_DIGGING:1:1800"
          - "JUMP:1:1800"
          - "SPEED:0:1800"
        actionBarMessage: "&aAn apple a day, yk what they say!"
    breakEvent:
      rewardChance: 1.0
      rewardMessage: "&6You found a superapple!"
      giveRewardItem: true
      rewardCommands: []
  "8":
    key: "KIT_KAT"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.kit_kat"
    usePerm: "item64.use.candy.kit_kat"
    item:
      mat: "DARK_OAK_SLAB"
      name: "&4Kit-Kat"
      lore:
        - "&f6 mins of"
        - "&f  Haste III"
        - "&f  Speed III"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "FAST_DIGGING:2:360"
          - "SPEED:2:360"
        actionBarMessage: "&0oOOOoOoOOoOooo &6You feel a sugar rush!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found some kit-kit!"
      giveRewardItem: true
      rewardCommands: []
  "9":
    key: "JOLLY_RANCHER"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.jolly_rancher"
    usePerm: "item64.use.candy.jolly_rancher"
    item:
      mat: "AMETHYST_SHARD"
      name: "&5Jolly Rancher"
      lore:
        - "&d7 mins of"
        - "&d  Resistance III"
        - "&d  Fire Resistance"
        - "&d  Slowness IV"
        - "&d  Mining Fatigue V"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "DAMAGE_RESISTANCE:2:420"
          - "FIRE_RESISTANCE:0:420"
          - "SLOW:3:420"
          - "SLOW_DIGGING:4:420"
        actionBarMessage: "&0oOoOoooOOoOOo &6You feel tough but sluggish!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a jolly rancher!"
      giveRewardItem: true
      rewardCommands: []
  "10":
    key: "CANDY_CARROT"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.candy_carrot"
    usePerm: "item64.use.candy.candy_carrot"
    item:
      mat: "GOLDEN_CARROT"
      name: "&6Candy Carrot"
      lore:
        - "&e8 mins of"
        - "&e  Night Vision III"
        - "&e  Resistance II"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "NIGHT_VISION:2:480"
          - "DAMAGE_RESISTANCE:1:480"
        actionBarMessage: "&0OoOooOOOOOoO &6Your eyes adjust to the darkness!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a candy carrot!"
      giveRewardItem: true
      rewardCommands: []
  "11":
    key: "MOONLIGHT_MUNCH"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.moonlight_munch"
    usePerm: "item64.use.candy.moonlight_munch"
    item:
      mat: "MUSHROOM_STEW"
      name: "&8Moonlight Munch"
      lore:
        - "&78 mins of"
        - "&7  Night Vision"
        - "&7  Regeneration II"
        - "&7  Glowing II"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "NIGHT_VISION:0:480"
          - "REGENERATION:1:480"
          - "GLOWING:1:480"
        actionBarMessage: "&0oOOOooOoOooo &6You glow under the moonlight!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a moonlight munch!"
      giveRewardItem: true
      rewardCommands: []
  "12":
    key: "PHANTOM_FRUIT"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.phantom_fruit"
    usePerm: "item64.use.candy.phantom_fruit"
    item:
      mat: "CHORUS_FRUIT"
      name: "&dPhantom Fruit"
      lore:
        - "&54 mins of"
        - "&5  Invisibility II"
        - "&5  Glowing"
        - "&5  Nausea"
        - "&5  Slow Falling VI"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "INVISIBILITY:1:240"
          - "GLOWING:0:240"
          - "CONFUSION:0:240"
          - "SLOW_FALLING:5:240"
        actionBarMessage: "&0oOOOooOoOooo &6You fade in and out of sight..."
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a phantom fruit!"
      giveRewardItem: true
      rewardCommands: []
  "13":
    key: "SPIDER_WEB_TAFFY"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.spider_web_taffy"
    usePerm: "item64.use.candy.spider_web_taffy"
    item:
      mat: "COBWEB"
      name: "&7Spider Web Taffy"
      lore:
        - "&f4 mins of"
        - "&f  Slowness VII"
        - "&f  Strength V"
        - "&f  Nausea"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "SLOW:6:240"
          - "INCREASE_DAMAGE:4:240"
          - "CONFUSION:0:240"
        actionBarMessage: "&0oOOOooOoOooo &6Sticky and strong!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found some spider web taffy!"
      giveRewardItem: true
      rewardCommands: []
  "14":
    key: "BROOMSTICK"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.BROOMSTICK"
    usePerm: "item64.use.candy.BROOMSTICK"
    item:
      mat: "BRUSH"
      name: "&bBroomstick"
      lore:
        - "&33 mins of"
        - "&3  Speed III"
        - "&3  Night Vision"
        - "&3  Slow Falling IV"
        - "&3  Jump Boost VII"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "SPEED:2:180"
          - "NIGHT_VISION:0:180"
          - "SLOW_FALLING:3:180"
          - "JUMP:6:180"
        actionBarMessage: "&0oOOOooOoOooo &6You feel as light as a feather!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a broomstick!"
      giveRewardItem: true
      rewardCommands: []
  "15":
    key: "GHOSTLY_GUMMY"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.ghostly_gummy"
    usePerm: "item64.use.candy.ghostly_gummy"
    item:
      mat: "SLIME_BALL"
      name: "&2Ghostly Gummy"
      lore:
        - "&a6 mins of"
        - "&a  Levitation III"
        - "&a  Invisibility"
        - "&a  Glowing"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "LEVITATION:2:360"
          - "INVISIBILITY:0:360"
          - "GLOWING:0:360"
        actionBarMessage: "&0oOOOooOoOaahh &6You get me so highhh!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a ghostly gummy!"
      giveRewardItem: true
      rewardCommands: []
  "16":
    key: "ZOMBIE_KUSH"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.zombie_kush"
    usePerm: "item64.use.candy.zombie_kush"
    item:
      mat: "GREEN_DYE"
      name: "&aZombie Kush"
      lore:
        - "&26 mins of"
        - "&2  Haste II"
        - "&2  Slowness"
        - "&2  Slow Falling"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "FAST_DIGGING:1:360"
          - "SLOW:0:360"
          - "SLOW_FALLING:0:360"
        actionBarMessage: "&0oOooOOooOoop &2The grass whispers as you move..."
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found some zombie kush!"
      giveRewardItem: true
      rewardCommands: []
  "17":
    key: "BEER"
    type: "CONSUMABLE"
    enabled: true
    givePerm: "item64.give.candy.beer"
    usePerm: "item64.use.candy.beer"
    item:
      mat: "HONEY_BOTTLE"
      name: "&fBeer"
      lore:
        - "&e8 mins of"
        - "&e  Slow Falling IV"
        - "&e  Slowness IV"
        - "&e  Nausea"
        - "&e  Regeneration IV"
        - "&e  Absorption II"
        - "&e  Mining Fatigue III"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "REGENERATION:3:480"
          - "ABSORPTION:1:480"
          - "SLOW_FALLING:3:480"
          - "SLOW:3:480"
          - "SLOW_DIGGING:2:480"
          - "CONFUSION:0:480"
        actionBarMessage: "&0oOOOOoooaaughhh &6You feel a bit tipsy!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found a bottle of beer!"
      giveRewardItem: true
      rewardCommands: []
  "18":
    key: "COKE"
    type: "USABLE"
    enabled: true
    givePerm: "item64.give.candy.coke"
    usePerm: "item64.use.candy.coke"
    item:
      mat: "SUGAR"
      name: "&9Coke"
      lore:
        - "&b6 mins of"
        - "&b  Speed V"
        - "&b  Jump Boost III"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
    usage:
      triggers:
        removeItemOnUse: true
        consoleCommands: []
        effects:
          - "SPEED:4:360"
          - "JUMP:2:360"
        actionBarMessage: "&0OOOOOOOOOOOOOO &6You're bursting with energy!!"
    breakEvent:
      rewardChance: 8.25
      rewardMessage: "&6You found some sugar!"
      giveRewardItem: true
      rewardCommands: []
  "19":
    key: "CRATE_KEY_REWARD"
    type: "NO_ITEM"
    enabled: false
    breakEvent:
      rewardChance: 0.0
      rewardMessage: "&6You found a crate key!"
      rewardCommands:
        - "crates givekey crate <player> 1"