# Item64 v0.2.8-beta by @tbm00
# https://github.com/tbm00/Item64

hooks:
  Vault:
    enabled: false
  GriefDefender:
    enabled: false
    ignoredClaims: []
  DeluxeCombat:
    enabled: false
    anchorExplosionPvpCheck: false

stopBlockPlace:
  - "REDSTONE_TORCH"

itemEntries:
  enabled: true
  '1':
    key: "FLAMETHROWER"
    type: "FLAME_PARTICLE" 
    enabled: true
    givePerm: "item64.give.flamethrower"
    usePerm: "item64.use.flamethrower"
    usage:
      moneyCost: 0.00
      hungerCost: 1
      cooldown: 0
      ammoItem:
        mat: "COAL"
        removeAmmoItem: true
      projectile:
        shotRandomness: 0.42
        extraPlayerDamage: 3.0
    item:
      mat: "REDSTONE_TORCH"
      name: "&6Flamethrower"
      lore:
        - "&8&oRequires Coal"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
  '2':
    key: "EXPLOSIVE_BOW"
    type: "EXPLOSIVE_ARROW"
    enabled: true
    givePerm: "item64.give.explosive_bow"
    usePerm: "item64.use.explosive_bow"
    usage:
      moneyCost: 0.00
      hungerCost: 0
      cooldown: 0
      ammoItem:
        mat: "BEDROCK"
        removeAmmoItem: true
      projectile:
        shotRandomness: 0.32
        extraPlayerDamage: 0.0
        explosiveArrow:
          power: 96
    item:
      mat:  "BOW"
      name: "&6Explosive Bow"
      lore:
        - "&8&oRequires Bedrock and Arrows"
      hideEnchants: false
      enchantments:
        - "UNBREAKING:5"
        - "MENDING:1"
  '3':
    key: "EXPLOSIVE_CROSSBOW"
    type: "EXPLOSIVE_ARROW"
    enabled: true
    givePerm: "item64.give.explosive_crossbow"
    usePerm: "item64.use.explosive_crossbow"
    usage:
      moneyCost: 0.00
      hungerCost: 5
      cooldown: 2
      ammoItem:
        mat: "TNT"
        removeAmmoItem: true
      projectile:
        shotRandomness: 0.2
        extraPlayerDamage: 0.0
        explosiveArrow:
          power: 4
    item:
      mat:  "CROSSBOW"
      name: "&6Explosive Crossbow"
      lore:
        - "&8&oRequires TNT and Arrows"
      hideEnchants: false
      enchantments:
        - "QUICK_CHARGE:5"
        - "MENDING:1"
  '4':
    key: "LIGHTNING_GUN"
    type: "LIGHTNING_PEARL"
    enabled: true
    givePerm: "item64.give.lightning_gun"
    usePerm: "item64.use.lightning_gun"
    usage:
      moneyCost: 0.00
      hungerCost: 2
      cooldown: 2
      ammoItem:
        mat: "ENDER_PEARL"
        removeAmmoItem: true
      projectile:
        shotRandomness: 0.22
        extraPlayerDamage: 5.0
    item:
      mat: "ECHO_SHARD"
      name: "&6Lightning Gun"
      lore:
        - "&8&oRequires Ender Pearls"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
  '5':
    key: "MAGIC_WAND"
    type: "RANDOM_POTION" 
    enabled: true
    givePerm: "item64.give.magic_wand"
    usePerm: "item64.use.magic_wand"
    usage:
      moneyCost: 0.00
      hungerCost: 2
      cooldown: 2
      ammoItem:
        mat: "POTION"
        removeAmmoItem: true
      projectile:
        shotRandomness: 0.22
        extraPlayerDamage: 6.0
        randomPotion:
          rightClickEffects:
            - "INCREASE_DAMAGE:1:30"
            - "HEAL:1:30"
            - "JUMP:1:30"
            - "SPEED:1:30"
            - "REGENERATION:1:30"
            - "FIRE_RESISTANCE:1:30"
            - "NIGHT_VISION:1:30"
            - "INVISIBILITY:1:30"
            - "ABSORPTION:1:30"
            - "SATURATION:1:30"
            - "SLOW_FALLING:1:30"
          leftClickEffects:
            - "SLOW:1:30"
            - "HARM:1:30"
            - "CONFUSION:1:30"
            - "BLINDNESS:1:30"
            - "HUNGER:1:30"
            - "WEAKNESS:1:30"
            - "POISON:1:30"
            - "LEVITATION:1:30"
            - "GLOWING:1:30"
    item:
      mat: "BRUSH"
      name: "&6Magic Wand"
      lore:
        - "&9Left Click for Aggressive Effects"
        - "&9Right Click for Positive Effects"
        - "&8&oRequires Potions or Water Bottles"
      hideEnchants: true
      enchantments:
        - "MENDING:1"
  '6':
    key: "HEALING_HONEY"
    type: "CONSUMABLE" 
    enabled: true
    givePerm: "item64.give.healing_honey"
    usePerm: "item64.use.healing_honey"
    usage:
      moneyCost: 0.00
      hungerCost: 0
      cooldown: 0
      ammoItem:
        mat: ""
        removeAmmoItem: true
      consumable:
        removeConsumableOnUse: true
        consoleCommands:
          - "itm heal <player> -fx"
        effects: []
    item:
      mat: "HONEY_BOTTLE"
      name: "&6Healing Honey"
      lore:
        - "&eRestores health, hunger,"
        - "&eand removes potions effects"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"
  '7':
    key: "SUPERAPPLE"
    type: "CONSUMABLE" 
    enabled: true
    givePerm: "item64.give.superapple"
    usePerm: "item64.use.superapple"
    usage:
      moneyCost: 0.00
      hungerCost: 0
      cooldown: 0
      ammoItem:
        mat: ""
        removeAmmoItem: true
      consumable:
        removeConsumableOnUse: true
        consoleCommands:
          - "itm heal <player>"
        effects:
          - "REGENERATION:1:1800"
          - "ABSORPTION:3:1800"
          - "DAMAGE_RESISTANCE:3:1800"
          - "FIRE_RESISTANCE:0:1800"
          - "INCREASE_DAMAGE:1:1800"
          - "FAST_DIGGING:1:60"
          - "JUMP:1:1800"
          - "SPEED:0:1800"
    item:
      mat: "ENCHANTED_GOLDEN_APPLE"
      name: "&6Superapple"
      lore:
        - "&e30 mins of"
        - "&e  Regeneration II"
        - "&e  Absorption IV"
        - "&e  Resistance IV"
        - "&e  Fire Resistance I"
        - "&e  Strength II"
        - "&e  Haste II"
        - "&e  Jump Boost II"
        - "&e  Speed I"
      hideEnchants: true
      enchantments:
        - "UNBREAKING:1"