name: Item64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.item64.Item64
api-version: 1.17
commands:
  itm:
    description: Base command for Item64
permissions:
  item64.help:
    description: Ability to display the command list
    default: op