name: Item64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.item64.Item64
api-version: 1.17
commands:
  itm:
    description: Base command for Item64
permissions:
  item64.help:
    description: Ability to display the command list
    default: op
  item64.give.explosive_arrow:
    description: Ability to give explosive arrow item
    default: op
  item64.give.lightning_pearl:
    description: Ability to give lightning pearl item
    default: op
  item64.give.random_potion:
    description: Ability to give random poiton item
    default: op
  item64.use.explosive_arrow:
    description: Ability to use explosive arrow item
    default: true
  item64.use.lightning_pearl:
    description: Ability to use lightning pearl item
    default: true
  item64.use.random_potion:
    description: Ability to use random poiton item
    default: true