name: Item64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.item64.Item64
api-version: 1.17
softdepend: [Vault, DeluxeCombat, GriefDefender, WorldGuard]
commands:
  itm:
    description: Base command for Item64
permissions:
  item64.help:
    description: Ability to display the command list
    default: op
  item64.heal:
    description: Ability to heal a player
    default: op
  item64.allowplace:
    description: Ability to place blacklisted blocks during BlockEvent
    default: op
  item64.allowbreak:
    description: Ability to break blacklisted blocks during BlockEvent
    default: op